### ISSUE TITLE
Can you add to this repo version 2.0.0 from the original ?

### ISSUE THREAD

**Issue by gggeek** [goetas/TemplatedUriBundle#4]
Atm I can not install any more f.e. https://packagist.org/packages/ezsystems/ezpublish-kernel, as it has a dependency on

`hautelook/templated-uri-bundle: ~1.0 | ~2.0`

**Comment by goetas** [comment]
What does it mean "i can not install it" which error are you getting? during `composer update` or `composer install` ?

**Comment by gggeek** [comment]
TBH it's a bit weird... I got the error during execution on a GitHub Action - but the same code worked when ran locally. Let me see if I can dig out the exact error message

**Comment by goetas** [comment]
can you just try to reset the composer cache?

**Comment by gggeek** [comment]
Found the logs: https://github.com/kaliop-uk/ezmigrationbundle/runs/5414603032?check_suite_focus=true

Indeed, installation happened from a pre-existing lock file, which might explain both the failure and the fact that, when I ran composer locally to regenerate the lock file, it actually worked...

(I know using a ready-made composer.lock file as part of the CI pipeline is far from ideal - I only had it in place for testing with php 5.6 as, on Travis, running composer install would just time out. I might revisit that now that I moved to GH...)

**Comment by goetas** [comment]
this is a side effect of https://github.com/goetas/TemplatedUriBundle/issues/1

please update your composer.lock file
